[memory_usage]
disabled = true

[custom.arc]
command = "arc info --json | jq '.branch' -r"
when = """ arc info """
style = "bold blue"
format = "on [ $output]($style) "
ignore_timeout = true

[nodejs]
disabled = true
