tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "mas"
brew "nvm"
brew "ssh-copy-id", link: true
brew "starship"
brew "zsh-autosuggestions"
brew "zsh"

cask "1password"
cask "cleanshot"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "iterm2"
cask "pixelsnap"
cask "raycast"
cask "rectangle"
cask "spotify"
cask "telegram"
cask "visual-studio-code"
cask "zoom"

mas "1Password for Safari", id: 1569813296
mas "Hand Mirror", id: 1502839586
mas "Paste", id: 967805235
mas "Things", id: 904280696
