tap "buo/cask-upgrade"

brew "fzf"
brew "ggh"
brew "mas"
brew "nvm"
brew "starship"
brew "zoxide"
brew "zsh"

cask "1password"
cask "anki"
cask "brave-browser"
cask "cleanshot"
cask "firefox"
cask "font-fira-code"
cask "iina"
cask "keka"
cask "notion"
cask "obsidian"
cask "pixelsnap"
cask "rectangle"
cask "spotify"
cask "telegram"
cask "visual-studio-code"
cask "wezterm"

mas "1Password for Safari", id: 1569813296
mas "Color Picker", id: 1545870783
mas "Hand Mirror", id: 1502839586
mas "Paste", id: 967805235
mas "Things", id: 904280696
