tap "tw93/tap/mole"
tap "xykong/tap"

brew "btop"
brew "fzf"
brew "ggh"
brew "gh"
brew "mas"
brew "nvm"
brew "rtk"
brew "starship"
brew "xykong/tap/flux-markdown"
brew "zoxide"
brew "zsh"

cask "1password"
cask "claude-code"
cask "cleanshot"
cask "firefox"
cask "font-fira-code"
cask "git"
cask "iina"
cask "keka"
cask "mole"
cask "notion"
cask "obsidian"
cask "pixelsnap"
cask "rectangle"
cask "spotify"
cask "telegram"
cask "visual-studio-code"
cask "wezterm"

mas "1Password for Safari", id: 1569813296
mas "Color Picker", id: 1545870783
mas "Hand Mirror", id: 1502839586
mas "Paste", id: 967805235
mas "Things", id: 904280696
mas "WhatsApp", id: 310633997
